name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy application
        run: |
          echo "Deploying to production..."
       
